### ISSUE TITLE
customer profile issue

### ISSUE THREAD

**Issue by hardik-tatvasoft** [livechat/agent-app-sdk#4]
Hi, 
I want to customer group info when click on customer row in customer module using webhook but not exits any kind of web hooks. After chatting with supporters his say use this 'https://developers.livechatinc.com/docs/agent-app-widgets/#events' event method for get 'customer_profile' but in this package not any option to set login/Auth credentials. 
So, how to know this event response from my chats/customers?? 
The second question is When the get 'customer_profile' event call response?? 
OR 
Is there any method/webhook/API to get 'customer_profile' detail in PHP.

**Comment by ZiggyKraus** [comment]
Hello @hardik-tatvasoft,

Thank you for reaching us out with this! As to your questions:

1) LiveChat widget does not include the customer's authorization within the chat widget itself, so we do not have a direct possibility to make sure that the person chatting with you is your actual customer. In order to work around that, you could either implement the chat widget only on the part of your website that is accessible only to your logged in customer or modify your LiveChat code so that it'll include the `lc.visitor` object, that can be automatically prepopulated with your customer's Name and Email – those data can be taken directly from your website's database. If you'd like to learn how to do that, here's the link to the documentation: https://developers.livechatinc.com/docs/js-api/#tracking-code

As to the PHP example, I'm afraid that we o not have such example available. And as to the event itself, the event will fire every time you are browsing through your customers' on the following sections:

- Chats;
- Customers;
- Archives.

If you'd like to learn more about the events available in Agent App Widget module, check out the following documentation, where you will find all the necessary info that you might need: https://developers.livechatinc.com/docs/agent-app-widgets/ 🙂
